namespace NotPseudo.CodeAnalysis
{
    public enum TokenType
    {
        Plus,
        Minus,
        Divide,
        Multiply,
        Colon,
        Assign,
        LeftParenthesis,
        RightParenthesis,
        NumberLiteral,
        StringLiteral,
        Identifier,
        DeclareKeyword,
        ForKeyword,
        ToKeyword,
        NextKeyword,
        OutputKeyword,
        IfKeyword,
        ThenKeyword,
        ElseKeyword,
        ElseIfKeyword,
        EndIfKeyword,
        LineFeed,
        EoF
    }
}